export interface MainRules {
    '1. Game Concepts': N1GameConcepts;
    '2. Parts of a Card': N2PartsOfACard;
    '3. Card Types': N3CardTypes;
    '4. Zones': N4Zones;
    '5. Turn Structure': N5TurnStructure;
    '6. Spells, Abilities, and Effects': N6SpellsAbilitiesAndEffects;
    '7. Additional Rules': N7AdditionalRules;
    '8. Multiplayer Rules': N8MultiplayerRules;
    '9. Casual Variants': N9CasualVariants;
    '~~': GeneratedType;
    glossary: Glossary;
}

export interface N1GameConcepts {
    '100. General': string[];
    '101. The Magic Golden Rules': string[];
    '102. Players': string[];
    '103. Starting the Game': string[];
    '104. Ending the Game': string[];
    '105. Colors': string[];
    '106. Mana': string[];
    '107. Numbers and Symbols': string[];
    '108. Cards': string[];
    '109. Objects': string[];
    '110. Permanents': string[];
    '111. Tokens': string[];
    '112. Spells': string[];
    '113. Abilities': string[];
    '114. Emblems': string[];
    '115. Targets': string[];
    '116. Special Actions': string[];
    '117. Timing and Priority': string[];
    '118. Costs': string[];
    '119. Life': string[];
    '120. Damage': string[];
    '121. Drawing a Card': string[];
    '122. Counters': string[];
    '~~': string[];
}

export interface N2PartsOfACard {
    '200. General': string[];
    '201. Name': string[];
    '202. Mana Cost and Color': string[];
    '203. Illustration': string[];
    '204. Color Indicator': string[];
    '205. Type Line': string[];
    '206. Expansion Symbol': string[];
    '207. Text Box': string[];
    '208. Power/Toughness': string[];
    '209. Loyalty': string[];
    '210. Hand Modifier': string[];
    '211. Life Modifier': string[];
    '212. Information Below the Text Box': string[];
    '122. Counters': string[];
}

export interface N3CardTypes {
    '300. General': string[];
    '301. Artifacts': string[];
    '302. Creatures': string[];
    '303. Enchantments': string[];
    '304. Instants': string[];
    '305. Lands': string[];
    '306. Planeswalkers': string[];
    '307. Sorceries': string[];
    '308. Tribals': string[];
    '309. Planes': string[];
    '310. Phenomena': string[];
    '311. Vanguards': string[];
    '312. Schemes': string[];
    '313. Conspiracies': string[];
    '212. Information Below the Text Box': string[];
}

export interface N4Zones {
    '400. General': string[];
    '401. Library': string[];
    '402. Hand': string[];
    '403. Battlefield': string[];
    '404. Graveyard': string[];
    '405. Stack': string[];
    '406. Exile': string[];
    '407. Ante': string[];
    '408. Command': string[];
    '313. Conspiracies': string[];
}

export interface N5TurnStructure {
    '500. General': string[];
    '501. Beginning Phase': string[];
    '502. Untap Step': string[];
    '503. Upkeep Step': string[];
    '504. Draw Step': string[];
    '505. Main Phase': string[];
    '506. Combat Phase': string[];
    '507. Beginning of Combat Step': string[];
    '508. Declare Attackers Step': string[];
    '509. Declare Blockers Step': string[];
    '510. Combat Damage Step': string[];
    '511. End of Combat Step': string[];
    '512. Ending Phase': string[];
    '513. End Step': string[];
    '514. Cleanup Step': string[];
    '408. Command': string[];
}

export interface N6SpellsAbilitiesAndEffects {
    '600. General': string[];
    '601. Casting Spells': string[];
    '602. Activating Activated Abilities': string[];
    '603. Handling Triggered Abilities': string[];
    '604. Handling Static Abilities': string[];
    '605. Mana Abilities': string[];
    '606. Loyalty Abilities': string[];
    '607. Linked Abilities': string[];
    '608. Resolving Spells and Abilities': string[];
    '609. Effects': string[];
    '610. One-Shot Effects': string[];
    '611. Continuous Effects': string[];
    '612. Text-Changing Effects': string[];
    '613. Interaction of Continuous Effects': string[];
    '614. Replacement Effects': string[];
    '615. Prevention Effects': string[];
    '616. Interaction of Replacement and/or Prevention Effects': string[];
    '514. Cleanup Step': string[];
}

export interface N7AdditionalRules {
    '700. General': string[];
    '701. Keyword Actions': string[];
    '702. Keyword Abilities': string[];
    '703. Turn-Based Actions': string[];
    '704. State-Based Actions': string[];
    '705. Flipping a Coin': string[];
    '706. Copying Objects': string[];
    '707. Face-Down Spells and Permanents': string[];
    '708. Split Cards': string[];
    '709. Flip Cards': string[];
    '710. Leveler Cards': string[];
    '711. Double-Faced Cards': string[];
    '712. Meld Cards': string[];
    '713. Checklist Cards': string[];
    '714. Saga Cards': string[];
    '715. Adventurer Cards': string[];
    '716. Controlling Another Player': string[];
    '717. Ending Turns and Phases': string[];
    '718. The Monarch': string[];
    '719. Restarting the Game': string[];
    '720. Subgames': string[];
    '721. Merging with Permanents': string[];
    '722. Taking Shortcuts': string[];
    '723. Handling Illegal Actions': string[];
    '616. Interaction of Replacement and/or Prevention Effects': string[];
}

export interface N8MultiplayerRules {
    '800. General': string[];
    '801. Limited Range of Influence Option': string[];
    '802. Attack Multiple Players Option': string[];
    '803. Attack Left and Attack Right Options': string[];
    '804. Deploy Creatures Option': string[];
    '805. Shared Team Turns Option': string[];
    '806. Free-for-All Variant': string[];
    '807. Grand Melee Variant': string[];
    '808. Team vs. Team Variant': string[];
    '809. Emperor Variant': string[];
    '810. Two-Headed Giant Variant': string[];
    '811. Alternating Teams Variant': string[];
    '723. Handling Illegal Actions': string[];
}

export interface N9CasualVariants {
    '900. General': string[];
    '901. Planechase': string[];
    '902. Vanguard': string[];
    '903. Commander': string[];
    '904. Archenemy': string[];
    '905. Conspiracy Draft': string[];
    '811. Alternating Teams Variant': string[];
}

export interface GeneratedType {
    '~~': string[];
}

export interface Glossary {
    '': string;
    Ability: string;
    'Ability Word': string;
    Absorb: string;
    Activate: string;
    'Activated Ability': string;
    'Activation Cost': string;
    'Active Player': string;
    'Active Player, Nonactive Player Order': string;
    'Active Team': string;
    Adapt: string;
    'Additional Cost': string;
    'Adventurer Card': string;
    Affinity: string;
    Afflict: string;
    Afterlife: string;
    Aftermath: string;
    'Alternating Teams Variant': string;
    'Alternative Cost': string;
    Amass: string;
    Amplify: string;
    'Anchor Word': string;
    Annihilator: string;
    Ante: string;
    'Any Target': string;
    'APNAP Order': string;
    Archenemy: string;
    Artifact: string;
    'Artifact Creature': string;
    'Artifact Land': string;
    'Artifact Type': string;
    'As Though': string;
    Ascend: string;
    Assemble: string;
    'Assign Combat Damage': string;
    Assist: string;
    'At End of Turn (Obsolete)': string;
    Attach: string;
    Attack: string;
    'Attack Alone': string;
    'Attack Left Option': string;
    'Attack Multiple Players Option': string;
    'Attack Right Option': string;
    'Attacking Creature': string;
    'Attacking Team': string;
    'Attacks and Isn’t Blocked': string;
    Aura: string;
    'Aura Swap': string;
    Awaken: string;
    'Banding, “Bands with Other”': string;
    'Base Power, Base Toughness': string;
    Basic: string;
    'Basic Landcycling': string;
    'Basic Land Type': string;
    'Battle Cry': string;
    Battlefield: string;
    Becomes: string;
    'Beginning of Combat Step': string;
    'Beginning Phase': string;
    Bestow: string;
    Block: string;
    'Block Alone': string;
    'Blocked Creature': string;
    'Blocking Creature': string;
    Bloodthirst: string;
    Bolster: string;
    'Booster Pack': string;
    Brawl: string;
    'Bury (Obsolete)': string;
    Bushido: string;
    Buyback: string;
    Card: string;
    'Card Pool': string;
    'Card Type': string;
    Cascade: string;
    Cast: string;
    'Caster (Obsolete)': string;
    'Casting Cost (Obsolete)': string;
    'Champion, Championed': string;
    'Change a Target': string;
    Changeling: string;
    'Chaos Ability': string;
    'Chaos Symbol': string;
    Characteristics: string;
    'Characteristic-Defining Ability': string;
    'Checklist Card': string;
    Cipher: string;
    'City’s Blessing': string;
    Clash: string;
    'Cleanup Step': string;
    'Collector Number': string;
    Color: string;
    Colorless: string;
    'Color Identity': string;
    'Color Indicator': string;
    'Combat Damage': string;
    'Combat Damage Step': string;
    'Combat Phase': string;
    Command: string;
    Commander: string;
    'Commander Ninjutsu': string;
    'Commander Tax': string;
    Companion: string;
    Concede: string;
    Conspiracy: string;
    'Conspiracy Draft': string;
    Conspire: string;
    Constructed: string;
    'Continuous Effect': string;
    'Continuous Artifact (Obsolete)': string;
    'Control, Controller': string;
    'Control Another Player': string;
    'Converted Mana Cost': string;
    Convoke: string;
    'Copiable Values': string;
    Copy: string;
    Cost: string;
    Counter: string;
    'Counts As (Obsolete)': string;
    Create: string;
    Creature: string;
    'Creature Type': string;
    Crew: string;
    'Cumulative Upkeep': string;
    Cycling: string;
    Damage: string;
    'Damage Assignment Order': string;
    Dash: string;
    Deal: string;
    Deathtouch: string;
    Deck: string;
    'Declare Attackers': string;
    'Declare Attackers Step': string;
    'Declare Blockers': string;
    'Declare Blockers Step': string;
    Defender: string;
    'Defending Player': string;
    'Defending Team': string;
    'Delayed Triggered Ability': string;
    Delve: string;
    Dependency: string;
    'Deploy Creatures Option': string;
    Destroy: string;
    Detain: string;
    Dethrone: string;
    Devoid: string;
    Devotion: string;
    Devour: string;
    Dies: string;
    Discard: string;
    'Double Agenda': string;
    'Double Strike': string;
    'Double-Faced Cards': string;
    Draft: string;
    'Draft Round': string;
    Draw: string;
    'Draw Step': string;
    Dredge: string;
    'During (Obsolete)': string;
    Echo: string;
    'EDH (Obsolete)': string;
    Effect: string;
    Embalm: string;
    Emblem: string;
    Emerge: string;
    Emperor: string;
    'Emperor Variant': string;
    Enchant: string;
    Enchantment: string;
    'Enchantment Type': string;
    Encoded: string;
    Encounter: string;
    'End of Combat Step': string;
    'End Step': string;
    'End the Combat Phase': string;
    'End the Turn': string;
    'Ending Phase': string;
    'Energy Symbol': string;
    'Enters the Battlefield': string;
    Entwine: string;
    Epic: string;
    Equip: string;
    Equipment: string;
    Escalate: string;
    Escape: string;
    Eternalize: string;
    'Evasion Ability': string;
    Event: string;
    Evoke: string;
    Evolve: string;
    Exalted: string;
    Exchange: string;
    Exert: string;
    'Excess Damage': string;
    Exile: string;
    'Expansion Symbol': string;
    Exploit: string;
    Explore: string;
    Extort: string;
    'Extra Turn': string;
    Fabricate: string;
    'Face Down': string;
    'Face Up': string;
    Fading: string;
    Fateseal: string;
    Fear: string;
    Fight: string;
    'First Strike': string;
    Flanking: string;
    Flash: string;
    Flashback: string;
    'Flavor Text': string;
    'Flip Cards': string;
    Flipped: string;
    'Flipping a Coin': string;
    Flying: string;
    'Food Token': string;
    Forecast: string;
    Forest: string;
    Forestcycling: string;
    Forestwalk: string;
    Fortification: string;
    Fortify: string;
    Frenzy: string;
    'Free-for-All': string;
    Fuse: string;
    'Fused Split Spell': string;
    General: string;
    'Generic Mana': string;
    'Global Enchantment (Obsolete)': string;
    Goad: string;
    Graft: string;
    'Grand Melee': string;
    Gravestorm: string;
    Graveyard: string;
    Hand: string;
    'Hand Modifier': string;
    Haste: string;
    Haunt: string;
    Hexproof: string;
    'Hidden Agenda': string;
    'Hidden Zone': string;
    Hideaway: string;
    Historic: string;
    Horsemanship: string;
    'Hybrid Card': string;
    'Hybrid Mana Symbols': string;
    If: string;
    'Illegal Action': string;
    'Illegal Target': string;
    Illustration: string;
    'Illustration Credit': string;
    Imprint: string;
    Improvise: string;
    'In Play (Obsolete)': string;
    'In Response To': string;
    Independent: string;
    Indestructible: string;
    Infect: string;
    Ingest: string;
    Instant: string;
    Instead: string;
    'Interrupt (Obsolete)': string;
    'Intervening “If” Clause': string;
    Intimidate: string;
    Investigate: string;
    Island: string;
    Islandcycling: string;
    'Islandhome (Obsolete)': string;
    Islandwalk: string;
    'Jump-Start': string;
    'Keyword Ability': string;
    'Keyword Action': string;
    'Keyword Counter': string;
    'Kicker, Kicked': string;
    Land: string;
    'Land Type': string;
    Landwalk: string;
    'Last Known Information': string;
    Layer: string;
    'Leaves the Battlefield': string;
    'Legal Text': string;
    'Legend (Obsolete)': string;
    Legendary: string;
    'Legend Rule': string;
    'Lethal Damage': string;
    'Level Symbol': string;
    'Level Up': string;
    'Leveler Cards': string;
    Library: string;
    'Life, Life Total': string;
    'Life Modifier': string;
    Lifelink: string;
    Limited: string;
    'Limited Range of Influence': string;
    'Linked Abilities': string;
    'Living Weapon': string;
    'Local Enchantment (Obsolete)': string;
    'London Mulligan': string;
    Loop: string;
    'Lose the Game': string;
    Loyalty: string;
    'Loyalty Ability': string;
    Madness: string;
    'Main Game': string;
    'Main Phase': string;
    Mana: string;
    'Mana Ability': string;
    'Mana Burn (Obsolete)': string;
    'Mana Cost': string;
    'Mana Pool': string;
    'Mana Source (Obsolete)': string;
    'Mana Symbol': string;
    Manifest: string;
    Match: string;
    'Maximum Hand Size': string;
    Megamorph: string;
    Meld: string;
    'Meld Cards': string;
    Melee: string;
    Menace: string;
    Mentor: string;
    'Merged Permanent': string;
    'Minimum Deck Size': string;
    Miracle: string;
    'Modal, Mode': string;
    Modular: string;
    Monarch: string;
    'Mono Artifact (Obsolete)': string;
    Monocolored: string;
    'Monocolored Hybrid Mana Symbols': string;
    Monstrosity: string;
    Monstrous: string;
    Morph: string;
    Mountain: string;
    Mountaincycling: string;
    Mountainwalk: string;
    Move: string;
    Mulligan: string;
    Multicolored: string;
    Multikicker: string;
    'Multiplayer Game': string;
    Mutate: string;
    'Mutating Creature Spell': string;
    Myriad: string;
    Name: string;
    Ninjutsu: string;
    'Nonbasic Land': string;
    'Nontraditional Magic Card': string;
    Object: string;
    Offering: string;
    'One-Shot Effect': string;
    Ongoing: string;
    'Opening Hand': string;
    Opponent: string;
    Option: string;
    Oracle: string;
    Outlast: string;
    'Outside the Game': string;
    Overload: string;
    Owner: string;
    Paired: string;
    'Paris Mulligan': string;
    'Partner, “Partner with [name]”': string;
    Pass: string;
    'Pass in Succession': string;
    Pay: string;
    Permanent: string;
    'Permanent Card': string;
    'Permanent Spell': string;
    'Permanently (Obsolete)': string;
    Persist: string;
    Phase: string;
    'Phased In, Phased Out': string;
    Phasing: string;
    Phenomenon: string;
    'Phyrexian Mana Symbol': string;
    'Phyrexian Symbol': string;
    Pile: string;
    Placed: string;
    Plains: string;
    Plainscycling: string;
    Plainswalk: string;
    'Planar Deck': string;
    'Planar Die': string;
    Plane: string;
    Planechase: string;
    Planeswalk: string;
    Planeswalker: string;
    'Planeswalker Symbol': string;
    'Planeswalker Type': string;
    'Planeswalker Uniqueness Rule (Obsolete)': string;
    Play: string;
    Player: string;
    'Poison Counter': string;
    Poisoned: string;
    Poisonous: string;
    'Poly Artifact (Obsolete)': string;
    Populate: string;
    'Postcombat Main Phase': string;
    Power: string;
    'Precombat Main Phase': string;
    Prevent: string;
    'Prevention Effect': string;
    Priority: string;
    Proliferate: string;
    Protection: string;
    Provoke: string;
    Prowess: string;
    Prowl: string;
    'Public Zone': string;
    Rampage: string;
    'Range of Influence': string;
    Reach: string;
    Rebound: string;
    Recover: string;
    'Redirect (Obsolete)': string;
    'Redirection Effect': string;
    'Reflexive Triggered Ability': string;
    Regenerate: string;
    Reinforce: string;
    'Reminder Text': string;
    'Removed from Combat': string;
    'Remove from the Game, Removed, Removed-from-the-Game Zone (Obsolete)': string;
    Renown: string;
    Renowned: string;
    'Replacement Effect': string;
    Replicate: string;
    Requirement: string;
    Resolve: string;
    'Restart the Game': string;
    Respond: string;
    Restriction: string;
    Retrace: string;
    Reveal: string;
    Riot: string;
    Ripple: string;
    'Rules Text': string;
    Sacrifice: string;
    Saga: string;
    Scavenge: string;
    Scheme: string;
    Scry: string;
    Search: string;
    'Set Aside (Obsolete)': string;
    'Set in Motion': string;
    Shadow: string;
    'Shared Life Total': string;
    'Shared Team Turns Option': string;
    Shortcut: string;
    Shroud: string;
    Shuffle: string;
    Sideboard: string;
    'Silver-Bordered': string;
    Skip: string;
    Skulk: string;
    Slivercycling: string;
    Snow: string;
    'Snow Mana Symbol': string;
    'Snow-Covered (Obsolete)': string;
    Sorcery: string;
    Soulbond: string;
    Soulshift: string;
    'Source of an Ability': string;
    'Source of Damage': string;
    'Special Action': string;
    Spectacle: string;
    Spell: string;
    'Spell Ability': string;
    'Spell Type': string;
    Splice: string;
    'Split Cards': string;
    'Split Second': string;
    Stack: string;
    'Starting Deck': string;
    'Starting Hand Size': string;
    'Starting Life Total': string;
    'Starting Player': string;
    'Starting Team': string;
    'State-Based Actions': string;
    'State Trigger': string;
    'Static Ability': string;
    Status: string;
    Step: string;
    Storm: string;
    Subgame: string;
    Subtype: string;
    'Successfully Cast (Obsolete)': string;
    'Summon (Obsolete)': string;
    'Summoning Sickness Rule': string;
    Sunburst: string;
    Supertype: string;
    'Supervillain Rumble': string;
    Support: string;
    Surge: string;
    Surveil: string;
    Suspend: string;
    Swamp: string;
    Swampcycling: string;
    Swampwalk: string;
    Tap: string;
    Tapped: string;
    'Tap Symbol': string;
    Target: string;
    Team: string;
    Teammate: string;
    'Team vs. Team Variant': string;
    'Text Box': string;
    'Text-Changing Effect': string;
    Threshold: string;
    'Timestamp Order': string;
    Token: string;
    'Tombstone Icon': string;
    'Total Casting Cost (Obsolete)': string;
    'Total Cost': string;
    'Totem Armor': string;
    Toughness: string;
    Tournament: string;
    'Tournament Rules': string;
    'Traditional Magic Card': string;
    Trample: string;
    Transfigure: string;
    Transform: string;
    Transmute: string;
    'Treasure Token': string;
    Tribal: string;
    Tribute: string;
    Trigger: string;
    'Trigger Condition': string;
    'Triggered Ability': string;
    'Trigger Event': string;
    'Turn-Based Actions': string;
    'Turn Markers': string;
    'Two-Headed Giant Variant': string;
    Type: string;
    'Type Icon': string;
    'Type Line': string;
    'Type-Changing Effect': string;
    Typecycling: string;
    Unattach: string;
    'Unblockable (Obsolete)': string;
    'Unblocked Creature': string;
    Undaunted: string;
    Undying: string;
    Unearth: string;
    Unflipped: string;
    Unleash: string;
    Unless: string;
    Untap: string;
    'Untap Step': string;
    'Untap Symbol': string;
    Untapped: string;
    'Upkeep Step': string;
    'Vancouver Mulligan': string;
    Vanguard: string;
    Vanishing: string;
    Variant: string;
    Vehicle: string;
    Vigilance: string;
    Vote: string;
    Wall: string;
    'Win the Game': string;
    Wither: string;
    Wizardcycling: string;
    World: string;
    'World Rule': string;
    X: string;
    Y: string;
    'You, Your': string;
    Zone: string;
    'Zone-Change Triggers': string;
}
